firebase:
  storage:
    bucket: data-4c0c3.firebasestorage.app

spring:
  application:
    name: 00data
  profiles:
    include: secret
#    active: dev

  # Thymeleaf 설정 (HTML 템플릿용)
  thymeleaf:
    cache: false # 개발환경에서는 false, 운영환경에서는 true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4

  servlet:
    multipart:
      max-file-size: 10MB      # 개별 파일 최대 크기
      max-request-size: 10MB   # 전체 요청 최대 크기

  sql:
    init:
      mode: never
#      data-locations: classpath:dummy-data/*.sql

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  ai:
    openai:
      base-url: https://api.perplexity.ai
      chat:
        completions-path: /chat/completions
        options:
          model: sonar-pro
          temperature: 0.3
          max-completion-tokens: 150
          top_p: 0.9
          frequency_penalty: 0.1
    model:
      embedding: none

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  upload:
    dir: /app/uploads
    base-url: /uploads


logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    com._data._data.eduinfo.service: DEBUG
    org.springframework.transaction: DEBUG
  file:
    path: /tmp/logs
