spring:
  application:
    name: 00data
  profiles:
    include: secret

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4

  sql:
    init:
      mode: always
      data-locations: classpath:dummy-data/*.sql

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  ai:
    openai:
      base-url: https://api.perplexity.ai
      chat:
        completions-path: /chat/completions
        options:
          model: llama-3.1-sonar-large-128k-online
          temperature: 0.2
          max-completion-tokens: 100
    model:
      embedding: none

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  upload:
    dir: uploads
    base-url: /uploads

logging:
  level:
    org.springframework.security: DEBUG
  file:
    path: /tmp/logs