INSERT IGNORE INTO nations (id, code, name, name_ko) VALUES
(1, 'KR', 'South Korea', '대한민국'),
(2, 'US', 'United States', '미국'),
(3, 'JP', 'Japan', '일본'),
(4, 'CN', 'China', '중국'),
(5, 'GB', 'United Kingdom', '영국'),
(6, 'DE', 'Germany', '독일'),
(7, 'FR', 'France', '프랑스'),
(8, 'CA', 'Canada', '캐나다'),
(9, 'AU', 'Australia', '호주'),
(10, 'IN', 'India', '인도'),
(11, 'BR', 'Brazil', '브라질'),
(12, 'RU', 'Russia', '러시아'),
(13, 'IT', 'Italy', '이탈리아'),
(14, 'ES', 'Spain', '스페인'),
(15, 'MX', 'Mexico', '멕시코'),
(16, 'NL', 'Netherlands', '네덜란드'),
(17, 'SE', 'Sweden', '스웨덴'),
(18, 'NO', 'Norway', '노르웨이'),
(19, 'CH', 'Switzerland', '스위스'),
(20, 'SG', 'Singapore', '싱가포르'),
(21, 'TH', 'Thailand', '태국'),
(22, 'VN', 'Vietnam', '베트남'),
(23, 'MY', 'Malaysia', '말레이시아'),
(24, 'PH', 'Philippines', '필리핀'),
(25, 'ID', 'Indonesia', '인도네시아'),
(26, 'TW', 'Taiwan', '대만'),
(27, 'HK', 'Hong Kong', '홍콩'),
(28, 'NZ', 'New Zealand', '뉴질랜드'),
(29, 'ZA', 'South Africa', '남아프리카공화국'),
(30, 'EG', 'Egypt', '이집트'),
(31, 'AE', 'United Arab Emirates', '아랍에미리트'),
(32, 'SA', 'Saudi Arabia', '사우디아라비아'),
(33, 'TR', 'Turkey', '터키'),
(34, 'GR', 'Greece', '그리스'),
(35, 'PT', 'Portugal', '포르투갈'),
(36, 'IE', 'Ireland', '아일랜드'),
(37, 'FI', 'Finland', '핀란드'),
(38, 'DK', 'Denmark', '덴마크'),
(39, 'BE', 'Belgium', '벨기에'),
(40, 'AT', 'Austria', '오스트리아'),
(41, 'PL', 'Poland', '폴란드'),
(42, 'CZ', 'Czech Republic', '체코'),
(43, 'HU', 'Hungary', '헝가리'),
(44, 'SK', 'Slovakia', '슬로바키아'),
(45, 'RO', 'Romania', '루마니아'),
(46, 'BG', 'Bulgaria', '불가리아'),
(47, 'HR', 'Croatia', '크로아티아'),
(48, 'SI', 'Slovenia', '슬로베니아'),
(49, 'LT', 'Lithuania', '리투아니아'),
(50, 'LV', 'Latvia', '라트비아'),
(51, 'EE', 'Estonia', '에스토니아'),
(52, 'IL', 'Israel', '이스라엘'),
(53, 'AR', 'Argentina', '아르헨티나'),
(54, 'CL', 'Chile', '칠레'),
(55, 'CO', 'Colombia', '콜롬비아'),
(56, 'PE', 'Peru', '페루'),
(57, 'VE', 'Venezuela', '베네수엘라'),
(58, 'UY', 'Uruguay', '우루과이'),
(59, 'EC', 'Ecuador', '에콰도르'),
(60, 'BO', 'Bolivia', '볼리비아');